import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertCircle, ArrowRight, Check, ChevronDown, CircleUserRound, Home, Loader2, Plus, RefreshCw, Search, Shield, Trash2, Users, X } from 'lucide-react';
import { getHousehold, addHouseholdMember, removeHouseholdMember, updateHousehold, updateHouseholdStatus } from '../api/households';
import { useAuthStore } from '../stores/authStore';
import type { HouseholdStatus } from '../types/household';

const transitions: Record<HouseholdStatus, HouseholdStatus[]> = {
  pending: ['active','suspended','closed'], active: ['suspended','inactive','closed'], suspended: ['active','inactive','closed'], inactive: ['active','closed'], closed: [],
};
const statusTone: Record<HouseholdStatus,string> = { pending:'bg-amber-50 text-amber-700 ring-amber-600/10', active:'bg-emerald-50 text-emerald-700 ring-emerald-600/10', suspended:'bg-orange-50 text-orange-700 ring-orange-600/10', inactive:'bg-slate-100 text-slate-600 ring-slate-500/10', closed:'bg-red-50 text-red-700 ring-red-600/10' };
function date(value:string|null){ if(!value)return '—'; const d=new Date(value); return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat(undefined,{day:'2-digit',month:'short',year:'numeric'}).format(d); }
function money(value:string|number|null){ if(value===null||value===undefined||value==='') return 'No shared cap'; return `${new Intl.NumberFormat(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value))} ETB`; }

export default function Households(){
 const {user}=useAuthStore(); const isSuper=user?.role==='super_admin'; const qc=useQueryClient();
 const [input,setInput]=useState(''); const [id,setId]=useState<number|null>(null); const [email,setEmail]=useState(''); const [notice,setNotice]=useState<string|null>(null); const [editing,setEditing]=useState(false); const [name,setName]=useState(''); const [budget,setBudget]=useState(''); const [preferences,setPreferences]=useState('{}');
 const query=useQuery({queryKey:['household',id],queryFn:()=>getHousehold(id!),enabled:id!==null}); const household=query.data;
 const setData=(h:any)=>{qc.setQueryData(['household',id],h);setNotice(null)};
 const update=useMutation({mutationFn:()=>updateHousehold(id!,{name:name.trim()||null,shared_budget_limit:budget===''?null:Number(budget),preferences:JSON.parse(preferences)}),onSuccess:h=>{setData(h);setEditing(false);setNotice('Household details updated.')}});
 const status=useMutation({mutationFn:(s:HouseholdStatus)=>updateHouseholdStatus(id!,s),onSuccess:h=>{setData(h);setNotice('Household status updated.')}});
 const add=useMutation({mutationFn:()=>addHouseholdMember(id!,email.trim()),onSuccess:h=>{setData(h);setEmail('');setNotice('Member added to the household.')}});
 const remove=useMutation({mutationFn:(memberId:number)=>removeHouseholdMember(id!,memberId),onSuccess:h=>{setData(h);setNotice('Household membership ended.')}});
 const open=(e:React.FormEvent)=>{e.preventDefault();const n=Number(input);if(Number.isInteger(n)&&n>0){setId(n);setNotice(null)}};
 const beginEdit=()=>{if(!household)return;setName(household.name??'');setBudget(household.shared_budget_limit==null?'':String(household.shared_budget_limit));setPreferences(JSON.stringify(household.preferences??{},null,2));setEditing(true)};
 return <div className="space-y-6">
  <header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-2 flex items-center gap-2 text-sm font-medium text-slate-500"><Home size={16}/> Household Operations</div><h1 className="text-2xl font-semibold tracking-tight text-slate-950">Households</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">Review household membership, shared budgets and preferences. Resource authorization remains enforced by Laravel.</p></div><form onSubmit={open} className="flex w-full max-w-sm gap-2"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input inputMode="numeric" value={input} onChange={e=>setInput(e.target.value.replace(/\D/g,''))} placeholder="Open household by ID" className="h-10 w-full rounded-lg border border-slate-200 bg-white pl-9 pr-3 text-sm outline-none focus:border-slate-400 focus:ring-2 focus:ring-slate-100"/></div><button className="h-10 rounded-lg bg-slate-950 px-4 text-sm font-semibold text-white hover:bg-slate-800">Open</button></form></header>
  {!id ? <section className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center"><div className="mx-auto mb-4 grid h-12 w-12 place-items-center rounded-xl bg-slate-100 text-slate-500"><Home size={22}/></div><h2 className="font-semibold text-slate-900">Open a household record</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">The current Laravel API exposes household resources by ID rather than a household collection endpoint. Use the operational record ID to inspect or manage a household.</p></section> : query.isLoading ? <Skeleton/> : query.isError ? <section className="flex min-h-64 flex-col items-center justify-center rounded-xl border border-slate-200 bg-white text-center"><div className="mb-3 rounded-full bg-red-50 p-3 text-red-600"><AlertCircle size={20}/></div><h2 className="font-semibold text-slate-900">Household could not be loaded</h2><p className="mt-1 text-sm text-slate-500">Check the API connection and your access, then retry.</p><button onClick={()=>query.refetch()} className="mt-4 inline-flex items-center gap-2 rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold"><RefreshCw size={15}/> Retry</button></section> : household ? <>
   <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-slate-950 text-white"><Home size={21}/></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold text-slate-950">{household.name||`Household #${household.id}`}</h2><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold capitalize ring-1 ${statusTone[household.status]}`}>{household.status.replaceAll('_',' ')}</span></div><p className="mt-1 text-sm text-slate-500">Household #{household.id} · Primary customer #{household.primary_customer_id} · Created {date(household.created_at)}</p></div></div><div className="flex gap-2"><button onClick={beginEdit} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Edit details</button>{isSuper&&<select value="" onChange={e=>e.target.value&&status.mutate(e.target.value as HouseholdStatus)} disabled={status.isPending} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700"><option value="">Change status</option>{transitions[household.status].map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select>}</div></div></div>
    <div className="grid border-b border-slate-200 md:grid-cols-3"><Metric label="Members" value={String(household.members.length)} icon={<Users size={17}/>}/><Metric label="Shared budget" value={money(household.shared_budget_limit)} icon={<Shield size={17}/>}/><Metric label="Primary account" value={`#${household.primary_customer_id}`} icon={<CircleUserRound size={17}/>}/></div>
    {notice&&<div className="flex items-center gap-2 border-b border-emerald-100 bg-emerald-50 px-5 py-3 text-sm font-medium text-emerald-800"><Check size={16}/>{notice}</div>}
    {editing&&<div className="border-b border-slate-200 bg-slate-50/70 p-5"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-semibold text-slate-900">Household details</h3><p className="text-xs text-slate-500">Preferences are sent as structured JSON to Laravel.</p></div><button onClick={()=>setEditing(false)} className="rounded-lg p-2 text-slate-400 hover:bg-white hover:text-slate-700"><X size={17}/></button></div><div className="grid gap-4 lg:grid-cols-3"><Field label="Name"><input value={name} onChange={e=>setName(e.target.value)} className="field"/></Field><Field label="Shared budget (ETB)"><input type="number" min="0" step="0.01" value={budget} onChange={e=>setBudget(e.target.value)} className="field"/></Field><Field label="Preferences JSON"><textarea value={preferences} onChange={e=>setPreferences(e.target.value)} rows={4} className="field resize-y font-mono text-xs"/></Field></div><div className="mt-4 flex justify-end"><button disabled={update.isPending} onClick={()=>{try{JSON.parse(preferences);update.mutate()}catch{setNotice('Preferences must contain valid JSON.')}}} className="inline-flex items-center gap-2 rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{update.isPending?<Loader2 className="animate-spin" size={15}/>:<Check size={15}/>} Save changes</button></div></div>}
   <div className="grid gap-0 lg:grid-cols-[1fr_340px]"><div className="border-r border-slate-200"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h3 className="font-semibold text-slate-900">Members</h3><p className="text-xs text-slate-500">Membership records are retained when a member leaves.</p></div><span className="rounded-md bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-600">{household.members.length} records</span></div><div className="divide-y divide-slate-100">{household.members.map(m=><div key={m.id} className="flex items-center justify-between gap-4 px-5 py-4"><div className="flex min-w-0 items-center gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-slate-100 text-slate-500"><CircleUserRound size={17}/></div><div className="min-w-0"><div className="font-semibold text-sm text-slate-900">Customer #{m.customer_id}</div><div className="mt-0.5 text-xs text-slate-500">{m.role} · Joined {date(m.joined_at)}{m.left_at?` · Left ${date(m.left_at)}`:''}</div></div></div><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold capitalize ${m.status==='active'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{m.status}</span>{isSuper&&m.role!=='primary'&&m.status==='active'&&<button title="End membership" onClick={()=>{if(confirm(`End membership for customer #${m.customer_id}?`))remove.mutate(m.id)}} disabled={remove.isPending} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={15}/></button>}</div></div>)}</div></div><aside className="bg-slate-50/60 p-5"><h3 className="font-semibold text-slate-900">Add member</h3><p className="mt-1 text-xs leading-5 text-slate-500">The account must already have a customer profile. Laravel prevents active membership in another household.</p><div className="mt-4"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="customer@example.com" className="field bg-white"/></div><button disabled={!email.trim()||add.isPending||!isSuper} onClick={()=>add.mutate()} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40"><Plus size={16}/>{add.isPending?'Adding…':'Add member'}</button>{!isSuper&&<p className="mt-2 text-[11px] text-slate-500">Your role has view access; member management requires the appropriate Laravel permission.</p>}<div className="mt-6 rounded-lg border border-slate-200 bg-white p-3"><div className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate-400">Preferences</div><pre className="mt-2 max-h-40 overflow-auto whitespace-pre-wrap break-words text-[11px] leading-5 text-slate-600">{JSON.stringify(household.preferences??{},null,2)}</pre></div></aside></div>
   </section>
 </> : null}
 </div>
}
function Metric({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className="flex items-center gap-3 border-r border-slate-200 px-5 py-4 last:border-r-0"><div className="grid h-9 w-9 place-items-center rounded-lg bg-slate-100 text-slate-500">{icon}</div><div><div className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">{label}</div><div className="mt-0.5 text-sm font-semibold text-slate-900">{value}</div></div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>}
function Skeleton(){return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="h-32 animate-pulse bg-slate-100"/><div className="grid gap-4 p-5 md:grid-cols-3"><div className="h-14 animate-pulse rounded bg-slate-100"/><div className="h-14 animate-pulse rounded bg-slate-100"/><div className="h-14 animate-pulse rounded bg-slate-100"/></div><div className="h-56 animate-pulse bg-slate-50"/></section>}
