import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, AlertTriangle, CheckCircle2, ClipboardList, HeartPulse, Loader2, RefreshCw, ShieldAlert, Target, XCircle } from 'lucide-react';
import { getAllergies, getAssessments, getGoals, getNutritionProfile, getPlanRequests, getPlans, getRestrictions, approveAllergy, approveRestriction, approvePlan, rejectAllergy, rejectRestriction, rejectPlan } from '../api/nutrition';
import type { CustomerAllergy, CustomerRestriction, NutritionPlan } from '../types/nutrition';

const tone=(status:string)=>status==='approved'||status==='active'||status==='achieved'||status==='fulfilled'?'bg-emerald-50 text-emerald-700 border-emerald-100':status==='pending'||status==='pending_review'||status==='draft'?'bg-amber-50 text-amber-700 border-amber-100':status==='rejected'||status==='abandoned'||status==='declined'?'bg-rose-50 text-rose-700 border-rose-100':'bg-slate-50 text-slate-600 border-slate-200';
const fmt=(v:string|null|undefined)=>v?new Date(v).toLocaleDateString(): '—';
const unwrap=(e:any)=>e?.response?.data?.message||e?.response?.data?.error||'The request could not be completed.';

export default function Nutrition(){
 const [customerId,setCustomerId]=useState(''); const [active,setActive]=useState('overview'); const [rejecting,setRejecting]=useState<{type:string,id:number}|null>(null); const [reason,setReason]=useState(''); const qc=useQueryClient(); const id=Number(customerId); const enabled=Number.isInteger(id)&&id>0;
 const profile=useQuery({queryKey:['nutrition','profile',id],queryFn:()=>getNutritionProfile(id),enabled});
 const assessments=useQuery({queryKey:['nutrition','assessments',id],queryFn:()=>getAssessments(id),enabled});
 const goals=useQuery({queryKey:['nutrition','goals',id],queryFn:()=>getGoals(id),enabled});
 const requests=useQuery({queryKey:['nutrition','requests',id],queryFn:()=>getPlanRequests(id),enabled});
 const plans=useQuery({queryKey:['nutrition','plans',id],queryFn:()=>getPlans(id),enabled});
 const allergies=useQuery({queryKey:['nutrition','allergies',id],queryFn:()=>getAllergies(id),enabled});
 const restrictions=useQuery({queryKey:['nutrition','restrictions',id],queryFn:()=>getRestrictions(id),enabled});
 const busy=profile.isFetching||assessments.isFetching||goals.isFetching||requests.isFetching||plans.isFetching||allergies.isFetching||restrictions.isFetching;
 const invalidate=()=>qc.invalidateQueries({queryKey:['nutrition',id]});
 const action=useMutation({mutationFn:async({type,id,decision,reason}:{type:string;id:number;decision:'approve'|'reject';reason?:string})=>{if(type==='allergy')return decision==='approve'?approveAllergy(id):rejectAllergy(id,reason!);if(type==='restriction')return decision==='approve'?approveRestriction(id):rejectRestriction(id,reason!);return decision==='approve'?approvePlan(id):rejectPlan(id,reason!);},onSuccess:()=>{setRejecting(null);setReason('');invalidate();}});
 const pendingSafety=useMemo(()=>[...(allergies.data||[]).filter(x=>x.status==='pending'),...(restrictions.data||[]).filter(x=>x.status==='pending')].length,[allergies.data,restrictions.data]);
 const refresh=()=>{if(enabled)invalidate()};
 return <div className="space-y-6">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full border border-emerald-100 bg-emerald-50 px-3 py-1 text-[11px] font-semibold uppercase tracking-[.14em] text-emerald-700"><ShieldAlert size={13}/> Safety-sensitive workspace</div><h1 className="text-2xl font-semibold tracking-tight text-slate-950">Nutrition</h1><p className="mt-1 max-w-2xl text-sm text-slate-500">Review a customer’s nutrition profile, clinical assessments, goals, safety records and plan lifecycle from one controlled workspace.</p></div><div className="flex gap-2"><input value={customerId} onChange={e=>setCustomerId(e.target.value.replace(/\D/g,''))} placeholder="Customer ID" inputMode="numeric" className="h-10 w-36 rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-slate-400"/><button disabled={!enabled||busy} onClick={refresh} className="inline-flex h-10 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-sm font-medium text-slate-700 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50"><RefreshCw size={16} className={busy?'animate-spin':''}/>Refresh</button></div></div>
  {!enabled?<div className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><Activity className="mx-auto text-slate-300" size={34}/><h2 className="mt-4 text-sm font-semibold text-slate-900">Open a customer nutrition record</h2><p className="mx-auto mt-1 max-w-md text-sm text-slate-500">Enter a customer ID above. Nutrition records are customer-scoped by the current Laravel API contract.</p></div>:<>
   <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={Activity} label="Weight" value={profile.data?.weight_kg!=null?`${profile.data.weight_kg} kg`:'—'}/><Metric icon={HeartPulse} label="Assessments" value={String(assessments.data?.length??0)}/><Metric icon={Target} label="Goals" value={String(goals.data?.length??0)}/><Metric icon={ClipboardList} label="Plans" value={String(plans.data?.length??0)}/><Metric icon={AlertTriangle} label="Pending safety" value={String(pendingSafety)}/></div>
   <div className="overflow-x-auto border-b border-slate-200"><div className="flex min-w-max gap-1">{[['overview','Overview'],['safety','Safety records'],['assessments','Assessments'],['goals','Goals'],['requests','Plan requests'],['plans','Plans']].map(([k,l])=><button key={k} onClick={()=>setActive(k)} className={`border-b-2 px-4 py-3 text-sm font-medium ${active===k?'border-slate-900 text-slate-950':'border-transparent text-slate-500 hover:text-slate-800'}`}>{l}</button>)}</div></div>
   {active==='overview'&&<Overview profile={profile.data} latestAssessment={assessments.data?.[0]} goals={goals.data||[]} activePlan={plans.data?.find(p=>p.status==='active')}/>} 
   {active==='safety'&&<Safety allergies={allergies.data||[]} restrictions={restrictions.data||[]} onAction={(type:string,id:number,decision:'approve'|'reject')=>decision==='reject'?setRejecting({type,id}):action.mutate({type,id,decision})} loading={action.isPending}/>} 
   {active==='assessments'&&<Assessments items={assessments.data||[]}/>} {active==='goals'&&<Goals items={goals.data||[]}/>} {active==='requests'&&<Requests items={requests.data||[]}/>} {active==='plans'&&<Plans items={plans.data||[]} onAction={(id:number,d:'approve'|'reject')=>d==='reject'?setRejecting({type:'plan',id}):action.mutate({type:'plan',id,decision:d})} loading={action.isPending}/>} 
  </>}
  {rejecting&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h3 className="text-base font-semibold text-slate-950">Reject record</h3><p className="mt-1 text-sm text-slate-500">A reason is required and will be sent to Laravel for the authoritative rejection workflow.</p><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={5} className="mt-4 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-slate-400" placeholder="Enter rejection reason..."/><div className="mt-4 flex justify-end gap-2"><button onClick={()=>{setRejecting(null);setReason('')}} className="rounded-lg px-4 py-2 text-sm font-medium text-slate-600 hover:bg-slate-100">Cancel</button><button disabled={reason.trim().length<3||action.isPending} onClick={()=>action.mutate({type:rejecting.type,id:rejecting.id,decision:'reject',reason:reason.trim()})} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">{action.isPending?'Rejecting…':'Reject record'}</button></div></div></div>}
 </div>
}
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between"><span className="text-xs font-medium text-slate-500">{label}</span><Icon size={17} className="text-slate-400"/></div><div className="mt-3 text-xl font-semibold tracking-tight text-slate-950">{value}</div></div>}
function Overview({profile,latestAssessment,goals,activePlan}:any){return <div className="grid gap-4 lg:grid-cols-2"><Section title="Nutrition profile"><Rows rows={[["Height",profile?.height_cm!=null?`${profile.height_cm} cm`:'—'],['Weight',profile?.weight_kg!=null?`${profile.weight_kg} kg`:'—'],['Activity level',profile?.activity_level||'—'],['Last updated',fmt(profile?.updated_at)] ]}/></Section><Section title="Current plan"><Rows rows={[["Status",activePlan?.status||'No active plan'],['Version',activePlan?`v${activePlan.version}`:'—'],['Calories',activePlan?.calorie_target!=null?`${activePlan.calorie_target} kcal/day`:'—'],['Protein',activePlan?.protein_target_g!=null?`${activePlan.protein_target_g} g/day`:'—']]}/></Section><Section title="Latest assessment"><Rows rows={[["Assessed",fmt(latestAssessment?.assessed_at)],['Conditions',latestAssessment?.conditions||'—'],['Medications',latestAssessment?.medications||'—'],['Vitals notes',latestAssessment?.vitals_notes||'—']]}/></Section><Section title="Goals"><div className="space-y-2">{goals.slice(0,4).map((g:any)=><div key={g.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3"><div><div className="text-sm font-medium">{g.goal_type}</div><div className="text-xs text-slate-500">{g.target_value??'—'} {g.target_unit||''}</div></div><span className={`rounded-full border px-2 py-1 text-[11px] font-semibold ${tone(g.status)}`}>{g.status}</span></div>)}{!goals.length&&<Empty text="No nutrition goals recorded."/>}</div></Section></div>}
function Safety({allergies,restrictions,onAction,loading}:any){return <div className="grid gap-4 lg:grid-cols-2"><SafetyTable title="Allergies" items={allergies} type="allergy" label={(x:any)=>x.allergen_name||x.custom_allergen_name||'Unnamed allergen'} meta={(x:any)=>x.severity||'severity not specified'} onAction={onAction} loading={loading}/><SafetyTable title="Restrictions" items={restrictions} type="restriction" label={(x:any)=>x.restriction_type} meta={(x:any)=>x.reason||x.notes||'No reason recorded'} onAction={onAction} loading={loading}/></div>}
function SafetyTable({title,items,type,label,meta,onAction,loading}:any){return <Section title={title}><div className="divide-y divide-slate-100">{items.map((x:any)=><div key={x.id} className="py-4 first:pt-0 last:pb-0"><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-semibold text-slate-900">{label(x)}</div><div className="mt-1 text-xs text-slate-500">{meta(x)}</div></div><span className={`rounded-full border px-2 py-1 text-[11px] font-semibold ${tone(x.status)}`}>{x.status}</span></div>{x.status==='pending'&&<div className="mt-3 flex gap-2"><button disabled={loading} onClick={()=>onAction(type,x.id,'approve')} className="inline-flex items-center gap-1.5 rounded-lg border border-emerald-200 px-3 py-1.5 text-xs font-semibold text-emerald-700 hover:bg-emerald-50"><CheckCircle2 size={14}/>Approve</button><button disabled={loading} onClick={()=>onAction(type,x.id,'reject')} className="inline-flex items-center gap-1.5 rounded-lg border border-rose-200 px-3 py-1.5 text-xs font-semibold text-rose-700 hover:bg-rose-50"><XCircle size={14}/>Reject</button></div>}</div>)}{!items.length&&<Empty text={`No ${title.toLowerCase()} recorded.`}/>}</div></Section>}
function Assessments({items}:any){return <Section title="Health assessments"><div className="divide-y divide-slate-100">{items.map((x:any)=><div key={x.id} className="grid gap-3 py-4 md:grid-cols-[150px_1fr]"><div className="text-xs text-slate-500">{fmt(x.assessed_at)}<br/>Recorded by #{x.recorded_by}</div><div className="grid gap-3 sm:grid-cols-3"><Field label="Conditions" value={x.conditions}/><Field label="Medications" value={x.medications}/><Field label="Vitals notes" value={x.vitals_notes}/></div></div>)}{!items.length&&<Empty text="No health assessments recorded."/>}</div></Section>}
function Goals({items}:any){return <Section title="Nutrition goals"><Table headers={['Goal','Target','Status','Source','Target date']} rows={items.map((x:any)=>[x.goal_type,`${x.target_value??'—'} ${x.target_unit||''}`,<span className={`rounded-full border px-2 py-1 text-[11px] font-semibold ${tone(x.status)}`}>{x.status}</span>,x.source,fmt(x.target_date)])}/></Section>}
function Requests({items}:any){return <Section title="Plan requests"><Table headers={['Request','Status','Notes','Created']} rows={items.map((x:any)=>[`#${x.id}`,<span className={`rounded-full border px-2 py-1 text-[11px] font-semibold ${tone(x.status)}`}>{x.status}</span>,x.notes||'—',fmt(x.created_at)])}/></Section>}
function Plans({items,onAction,loading}:any){return <Section title="Nutrition plans"><div className="divide-y divide-slate-100">{items.map((x:any)=><div key={x.id} className="py-5 first:pt-0"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-sm font-semibold">Version {x.version} <span className="font-normal text-slate-400">· Plan #{x.id}</span></div><div className="mt-1 text-xs text-slate-500">Created {fmt(x.created_at)} · Author #{x.created_by??'—'}</div></div><span className={`rounded-full border px-2.5 py-1 text-[11px] font-semibold ${tone(x.status)}`}>{x.status}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-4"><Field label="Calories" value={x.calorie_target!=null?`${x.calorie_target} kcal/day`:'—'}/><Field label="Protein" value={x.protein_target_g!=null?`${x.protein_target_g} g`:'—'}/><Field label="Carbs" value={x.carbs_target_g!=null?`${x.carbs_target_g} g`:'—'}/><Field label="Fat" value={x.fat_target_g!=null?`${x.fat_target_g} g`:'—'}/></div>{x.meal_structure&&<p className="mt-3 text-sm text-slate-600"><span className="font-medium text-slate-800">Meal structure:</span> {x.meal_structure}</p>}{x.guidance_notes&&<p className="mt-2 text-sm text-slate-600"><span className="font-medium text-slate-800">Guidance:</span> {x.guidance_notes}</p>}{x.status==='pending_review'&&<div className="mt-4 flex gap-2"><button disabled={loading} onClick={()=>onAction(x.id,'approve')} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white">Approve plan</button><button disabled={loading} onClick={()=>onAction(x.id,'reject')} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-semibold text-rose-700 hover:bg-rose-50">Reject</button></div>}</div>)}{!items.length&&<Empty text="No nutrition plans recorded."/>}</div></Section>}
function Section({title,children}:{title:string;children:any}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 md:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-sm font-semibold text-slate-950">{title}</h2></div>{children}</section>}
function Rows({rows}:{rows:string[][]}){return <div className="divide-y divide-slate-100">{rows.map(([a,b])=><div key={a} className="flex justify-between gap-4 py-3 first:pt-0 last:pb-0"><span className="text-xs text-slate-500">{a}</span><span className="max-w-[70%] text-right text-sm font-medium text-slate-800">{b}</span></div>)}</div>}
function Field({label,value}:{label:string;value:any}){return <div><div className="text-[11px] font-medium uppercase tracking-wide text-slate-400">{label}</div><div className="mt-1 text-sm text-slate-700">{value||'—'}</div></div>}
function Table({headers,rows}:{headers:string[];rows:any[][]}){return <div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead><tr className="border-b border-slate-100 text-[11px] uppercase tracking-wide text-slate-400">{headers.map(h=><th key={h} className="pb-3 pr-5 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} className="py-3 pr-5 text-slate-700">{c}</td>)}</tr>)}</tbody></table></div>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-slate-200 px-4 py-8 text-center text-sm text-slate-400">{text}</div>}
